### ISSUE TITLE
TypeError: run_localtunnel() missing 1 required positional argument: 'local_host'

### ISSUE THREAD

**Issue by pritisolanki** [redevil1/flask-localtunnel#5]
Hi,

I am trying to use lt in google colab and getting error. Following is the code
```
!pip install flask-localtunnel
from flask_lt import run_with_lt
run_with_lt(app)

if __name__ == "__main__":
  app.run()
```

Not sure why would I be asked for local_host? If I pass that in app.run , it breaks the code with error. Can you please suggest what I might be doing wrong or how can I pass on  local_host setting.

**Comment by tejas36026** [comment]
same here

**Comment by jakbin** [comment]
i have fix that error . please install latest version  and let me if it works .
